spring.application.name=CategoryManagement
# Port chạy ứng dụng
server.port=8080

# Tắt cache Thymeleaf để HTML cập nhật ngay khi sửa code[cite: 1]
spring.thymeleaf.cache=false

# Cấu hình SQL Server
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=CategoryManagementDB;encrypt=true;trustServerCertificate=true;
spring.datasource.username=sa
spring.datasource.password=2006
spring.datasource.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver

# Hibernate - Tự động tạo bảng từ Entity Java[cite: 1]
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true