spring.application.name=ProductManagement_1509
server.port=8080

# Cấu hình Thymeleaf
spring.thymeleaf.cache=false

# Cấu hình SQL Server (Tạo database ProductVD12DB trong SSMS)
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=ProductManagement_1509;encrypt=true;trustServerCertificate=true;
spring.datasource.username=sa
spring.datasource.password=2006
spring.datasource.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver

# Cấu hình JPA
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect

# Cấu hình giới hạn dung lượng File Upload[cite: 2]
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=10MB